server:
  port: 7003

mybatis-plus:
  configuration:
    #该配置用于打印执行的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: datas-biz
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-dev.yml
      - nacos:${spring.application.name}-dev.yml
#  datasource:  # 示例数据源配置，注意修改
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://pig-mysql:3306/covid_spider?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  shardingsphere:
    enabled: true
    props:
      sql-show: true
    datasource:
      names: master, slave0
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/covid_spider?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/covid_spider?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    rules:
      #读写分离配置
      readwriteSplitting:
          data-sources:
            ms:
              type: Static
              loadBalancerName: round-robin
              props:
                write-data-source-name: master
                read-data-source-names: slave0
            load-balancers:
              my: # 负载均衡算法名称
                type: ROUND_ROBIN # 负载均衡算法类型
                props:
                  default: 0
# spring security 配置
security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server

